version: '3'

services:
  app:
    image: pistis
    build:
      context: .
    volumes:
      - ./store:/app/store

  proxy:
    image: nginx:1.13-alpine
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - app
    ports:
      - 80:80
